[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    "test.py",
    "tests",
    "venv",
    "env",
    ".venv",
    ".env",
]

src=["my008"]
